#spring boot
spring.datasource.url: jdbc:mysql://47.98.132.196:3306/vueblog2
spring.datasource.username: root
spring.datasource.password: anjie123B
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
#oracle配置
#spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
#spring.datasource.url=jdbc\:oracle\:thin:@localhost\:1521\:XE
#spring.datasource.username=system
#spring.datasource.password=oracle
#根据实体类自动维护表：create-启动删除上次生成的表
#                   create-drop:启动时根据实体类生成表，sessionFactory关闭时表中数据会被清除
#                   update：更新表
#                   validate：验证实体类和数据表是否匹配
#                   none：不采取任何操作
spring.jpa.hibernate.ddl-auto: create
#控制台输出sql
spring.jpa.show-sql: true
#json格式美化
spring.jackson.serialization.indent-output: true
＃设置spring-boot编码格式
server.tomcat.uri-encoding: UTF-8
spring.http.encoding.charset: UTF-8
spring.http.encoding.enabled: true
spring.http.encoding.force: true
spring.messages.encoding: UTF-8